LOCATIONS = [
    'Langa',
    'Philippi',
    'Lavender Hill',
    'Manenberg',
    'Hanover Park',
    'Bridgetown',
    'Bonteheuwel',
    'Lotus River',
    'Erica Township',
    'Lakeside',
    'Morning Star',
    'Silvertown',
    'Cape Farms',
    'Kalksteenfontein',
    'Browns Farm',
    'Bishop Lavis',
    'Ferness Estate',
    'Bel Ombre',
    'Schaap Kraal',
    'Wetton',
    'Retreat',
    'Belhar',
    'Wynberg',
    'Seawinds',
    'Kirstenhof',
    'Crawford',
    'Fresnaye',
    'Heathfield',
    'Elfindale',
    'Southfield',
    'Maitland',
    'Meadowridge',
    'Marina Da Gama',
    'Rylands',
    'Foreshore',
    'Zonnebloem',
    'Pinelands',
    'Wynberg Upper',
    'Rondebosch East',
    'Kenilworth Upper',
    'Observatory',
    'Bo Kaap',
    'Diep River',
    'Bergvliet',
    'Newlands',
    'Muizenberg',
    'Kenilworth',
    'Rondebosch Village',
    'Ottery',
    'Kalk Bay',
    'Fairways',
    'Woodstock',
    'Thornton',
    'Grassy Park',
    'Gleemoor',
    'Walmer Estate',
    'Stonehurst Mountain Estate',
    'Capricorn',
    'Costa Da Gama',
    'Mowbray',
    'Yorkshire Estate',
    'Coniston Park',
    'Silvertree Estate',
    'Heideveld',
    'Nieuwe Steenberg',
    'Ndabeni',
    'Bishopscourt Village',
    'Rosebank',
    'Salt River',
    'Bakoven',
    'Zwaanswyk',
    'Ocean View',
    'Zeekoevlei',
    'Lansdowne',
    'Kenwyn',
    'Harfield Village',
    'Kensington',
    'Silverhurst Estate',
    'Athlone',
    'Montana',
    'Surrey Estate',
    'St James',
    'Pelican Park',
    'Punts Estate',
    'Kreupelbosch',
    'Vanguard',
    'Nooitgedacht',
    'Belthorne Estate',
    'Steenberg Golf Estate',
    'Hazendal',
    'Zandvlei',
    'Philadelphia',
    'Windermere',
    'University Estate',
    'Dennedal',
    'Ottery East',
    'Belgravia',
    'Frogmore Estate',
    'Sybrand Park',
    'Welcome',
    'Penlyn Estate',
    'Belle Constantia',
    'Cape Town City Centre',
    'Rondebosch Park Estate',
    'Westlake',
    'Trovato',
    'Plumstead',
    'Tokai',
    'Vredehoek',
    'Claremont',
    'Rondebosch',
    'Oranjezicht',
    'Claremont Upper',
    'De Waterkant',
    'Tamboerskloof',
    'Green Point',
    'Gardens',
    'Higgovale',
    'Mouille Point',
    'Bantry Bay',
    'Three Anchor Bay',
    'Sea Point',
    'Constantia',
    'Waterfront',
    'Clifton',
    'Llandudno',
    'Camps Bay',
    'Bishopscourt'
]
